# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs-apt"
      ref: "6.3.0"
    mysql:
      repo: "puppetlabs-mysql"
      ref: "10.2.1"
    locales:
      repo: "saz-locales"
      ref: "2.5.1"
    timezone:
      repo: "saz-timezone"
      ref: "5.1.1"
    ssh:
      repo: "saz-ssh"
      ref: "6.0.0"
    sshkeys_core:
      repo: "puppetlabs-sshkeys_core"
      ref: "1.0.3"
    cron_core:
      repo: "puppetlabs-cron_core"
      ref: "1.0.3"
    systemd:
      repo: "camptocamp-systemd"
      ref: "2.2.0"
    chrony:
      repo: "aboe-chrony"
      ref: "0.2.4"
    nginx:
      repo: "puppet-nginx"
      ref: "0.16.0"
    letsencrypt:
      repo: "puppet-letsencrypt"
      ref: "5.0.0"
    nodejs:
      repo: "puppet-nodejs"
      ref: "7.0.1"
    composer:
      repo: "willdurand-composer"
      ref: "1.2.7"
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "5.2.0"
    translate:
      repo: "puppetlabs-translate"
      ref: "1.2.0"
    inifile:
      repo: "puppetlabs-inifile"
      ref: "2.5.0"
    concat:
      repo: "puppetlabs-concat"
      ref: "5.3.0"
    vcsrepo:
      repo: "puppetlabs-vcsrepo"
      ref: "2.4.0"
    epel:
      repo: "stahnma-epel"
      ref: "1.3.1"
    debconf:
      repo: "stm-debconf"
      ref": "2.3.0"
    remote_file:
      repo: "lwf-remote_file"
      ref": "1.1.3"
